# Generated by Django 3.2.7 on 2021-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('isbn', models.CharField(blank=True, max_length=10)),
                ('imagen', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('autor', models.ManyToManyField(to='libreria.Autores')),
            ],
        ),
    ]
