# Generated by Django 3.2.7 on 2021-09-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='autor',
        ),
        migrations.AddField(
            model_name='libros',
            name='autor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
